from .models import Product, PortfolioItem, Molding, MatColorGroup, MatColor, Service

products: list[Product] = [
    Product(id=1, file="20180125_170337.jpg", title="Marco Nogal Clasico", category="Enmarcado", desc="Marco de nogal profundo hecho a medida, perfecto para retratos familiares.", price=850),
    Product(id=2, file="20180202_164440.jpg", title="Caja de Sombras Roble", category="Enmarcado", desc="Caja de sombras de roble rustico acabada a mano para preservar recuerdos.", price=1200),
    Product(id=3, file="20180205_165928.jpg", title="Marco Galeria Moderno", category="Enmarcado", desc="Marco de galeria negro con montaje de archivo de calidad museo.", price=950),
    Product(id=4, file="20180208_184850.jpg", title="Acabado Dorado Ornamentado", category="Restauracion", desc="Restauracion de marco antiguo con hoja de oro, devolviendo la historia a la vida.", price=1500),
    Product(id=5, file="20180208_184953.jpg", title="Maple Minimalista", category="Enmarcado", desc="Marco de madera de maple natural con acabado transparente contemporaneo.", price=750),
    Product(id=6, file="20180215_185709.jpg", title="Blanco Vintage", category="Enmarcado", desc="Marco blanco desgastado perfecto para decoracion costera o campestre.", price=680),
    Product(id=7, file="20180329_104214.jpg", title="Flotador para Canvas", category="Montaje", desc="Marco flotador personalizado que da la ilusion del canvas flotando.", price=1100),
    Product(id=8, file="20180423_193653.jpg", title="Presentacion Doble Mat", category="Enmarcado", desc="Elegante doble matting en crema y azul marino para acentuar la obra.", price=900),
    Product(id=9, file="20180503_192206.jpg", title="Restauracion de Herencia", category="Restauracion", desc="Trabajo detallado de restauracion en un marco danado de mediados de siglo.", price=1800),
    Product(id=10, file="20180507_183731.jpg", title="Certificado Corporativo", category="Enmarcado", desc="Enmarcado profesional para diplomas y premios corporativos.", price=550),
    Product(id=11, file="20180509_151018.jpg", title="Union de Esquinas Artesanal", category="Enmarcado", desc="Mostrando nuestras tecnicas de precision en union de esquinas.", price=1050),
    Product(id=12, file="20180619_213821.jpg", title="Gran Formato Personalizado", category="Enmarcado", desc="Marco personalizado reforzado para fotografia de gran escala.", price=2200),
    Product(id=13, file="20180623_194708.jpg", title="Exhibidor de Jersey", category="Montaje", desc="Caja de sombras profunda con vidrio UV para proteger un jersey firmado.", price=1600),
    Product(id=14, file="20180714_222234.jpg", title="Mezcla Eclectica", category="Enmarcado", desc="Una combinacion unica de elementos modernos y tradicionales.", price=980),
    Product(id=15, file="20180819_145754.jpg", title="Preservacion de Arte Fino", category="Enmarcado", desc="Enmarcado de conservacion con materiales libres de acido para arte valioso.", price=1350),
    Product(id=16, file="20180831_193243.jpg", title="Textura y Profundidad", category="Enmarcado", desc="Perfil de marco texturizado para agregar profundidad a una impresion plana.", price=870),
    Product(id=17, file="DSC_0022.JPG", title="Coleccion Pared Galeria", category="Enmarcado", desc="Parte de un conjunto cohesivo para la pared de galeria de un cliente.", price=920),
    Product(id=18, file="DSC_0100.JPG", title="Tallado en Madera Detallado", category="Enmarcado", desc="Detalles intricados de tallado en madera en un marco personalizado.", price=1450),
    Product(id=19, file="DSC_0871.JPG", title="Marco Acento Metalico", category="Enmarcado", desc="Marco con acabado de metal cepillado para interiores industriales modernos.", price=1050),
    Product(id=20, file="FB_IMG_1516136999466.jpg", title="Enmarcado de Espejo", category="Enmarcado", desc="Transformando un espejo simple en una pieza de declaracion.", price=1150),
    Product(id=21, file="IMG_20180208_185310_102.jpg", title="Acabado Tenido a Mano", category="Enmarcado", desc="Tinte mezclado a medida para combinar con los muebles existentes del cliente.", price=980),
    Product(id=22, file="IMG-20180414-WA0023.jpg", title="Serie Foto de Boda", category="Enmarcado", desc="Enmarcado elegante y romantico para fotografia de boda.", price=1100),
    Product(id=23, file="IMG-20180414-WA0024.jpg", title="Herencia Familiar", category="Enmarcado", desc="Preservando fotografias familiares antiguas con estandares de archivo.", price=850),
    Product(id=24, file="IMG-20180415-WA0020.jpg", title="Exhibicion de Artista", category="Enmarcado", desc="Enmarcado disenado para dejar que el arte hable por si mismo.", price=780),
    Product(id=25, file="IMG-20180526-WA0038.jpg", title="Color Audaz", category="Enmarcado", desc="Un color vibrante de marco elegido para resaltar contra una pared neutral.", price=720),
    Product(id=26, file="IMG-20180528-WA0014.jpg", title="Elegancia Sutil", category="Enmarcado", desc="Diseno discreto que complementa en lugar de competir.", price=690),
    Product(id=27, file="IMG-20180611-WA0045.jpg", title="Proceso de Taller", category="Restauracion", desc="Detras de escenas en nuestro taller de madera.", price=600),
    Product(id=28, file="IMG-20180611-WA0046.jpg", title="Corte de Precision", category="Restauracion", desc="Asegurando que cada angulo sea perfecto para una union sin costuras.", price=650),
    Product(id=29, file="IMG-20180611-WA0047.jpg", title="Ensamblaje Final", category="Restauracion", desc="Los toques finales antes de que la pieza este lista para entrega.", price=700),
    Product(id=30, file="IMG-20180908-WA0022.jpeg", title="Pieza de Exhibicion", category="Restauracion", desc="La obra terminada lista para exhibir en el hogar del cliente.", price=950),
]

portfolio_items: list[PortfolioItem] = [
    PortfolioItem(id=1, file="20180125_170337.jpg", title="Classic Walnut Frame", category="Framing", desc="A timeless deep walnut frame custom-built for a family portrait.", aspect="aspect-square"),
    PortfolioItem(id=2, file="20180202_164440.jpg", title="Rustic Oak Shadowbox", category="Framing", desc="Hand-finished rustic oak shadowbox designed to preserve memorabilia.", aspect="aspect-[3/4]"),
    PortfolioItem(id=3, file="20180205_165928.jpg", title="Modern Gallery Frame", category="Framing", desc="Sleek black gallery frame with museum-grade archival matting.", aspect="aspect-[4/3]"),
    PortfolioItem(id=4, file="20180208_184850.jpg", title="Ornate Gold Finish", category="Maintenance", desc="Restoration of an antique gold-leaf frame, bringing history back to life.", aspect="aspect-square"),
    PortfolioItem(id=5, file="20180208_184953.jpg", title="Minimalist Maple", category="Framing", desc="Natural maple wood frame with a clear finish for a contemporary look.", aspect="aspect-[3/4]"),
    PortfolioItem(id=6, file="20180215_185709.jpg", title="Vintage White Wash", category="Framing", desc="Distressed white frame perfect for coastal or farmhouse decor.", aspect="aspect-[4/3]"),
    PortfolioItem(id=7, file="20180329_104214.jpg", title="Deep Canvas Floater", category="Mounting", desc="A custom floater frame that gives the illusion of the canvas floating inside.", aspect="aspect-square"),
    PortfolioItem(id=8, file="20180423_193653.jpg", title="Double Mat Presentation", category="Framing", desc="Elegant double matting in cream and navy to accent the artwork.", aspect="aspect-[3/4]"),
    PortfolioItem(id=9, file="20180503_192206.jpg", title="Heirloom Restoration", category="Maintenance", desc="Detailed restoration work on a damaged mid-century frame.", aspect="aspect-[4/3]"),
    PortfolioItem(id=10, file="20180507_183731.jpg", title="Corporate Certificate", category="Framing", desc="Professional framing for diplomas and corporate awards.", aspect="aspect-square"),
    PortfolioItem(id=11, file="20180509_151018.jpg", title="Artisan Corner Joinery", category="Framing", desc="Showcasing our precision corner joinery techniques.", aspect="aspect-[3/4]"),
    PortfolioItem(id=12, file="20180619_213821.jpg", title="Large Format Custom", category="Framing", desc="Oversized custom frame built reinforced for large-scale photography.", aspect="aspect-[4/3]"),
    PortfolioItem(id=13, file="20180623_194708.jpg", title="Sports Jersey Display", category="Mounting", desc="Deep shadowbox with UV glass to protect a signed jersey.", aspect="aspect-square"),
    PortfolioItem(id=14, file="20180714_222234.jpg", title="Eclectic Mix", category="Framing", desc="A unique combination of modern and traditional elements.", aspect="aspect-[3/4]"),
    PortfolioItem(id=15, file="20180819_145754.jpg", title="Fine Art Preservation", category="Framing", desc="Conservation framing using acid-free materials to protect valuable art.", aspect="aspect-[4/3]"),
    PortfolioItem(id=16, file="20180831_193243.jpg", title="Texture & Depth", category="Framing", desc="Using a textured frame profile to add depth to a flat print.", aspect="aspect-square"),
    PortfolioItem(id=17, file="DSC_0022.JPG", title="Gallery Wall Collection", category="Framing", desc="Part of a cohesive set designed for a client's gallery wall.", aspect="aspect-[3/4]"),
    PortfolioItem(id=18, file="DSC_0100.JPG", title="Detailed Wood Carving", category="Framing", desc="Close-up of intricate wood carving details on a custom frame.", aspect="aspect-[4/3]"),
    PortfolioItem(id=19, file="DSC_0871.JPG", title="Metallic Accent Frame", category="Framing", desc="Brushed metal finish frame suitable for modern industrial interiors.", aspect="aspect-square"),
    PortfolioItem(id=20, file="FB_IMG_1516136999466.jpg", title="Custom Mirror Framing", category="Framing", desc="Transforming a simple mirror into a statement piece.", aspect="aspect-[3/4]"),
    PortfolioItem(id=21, file="IMG_20180208_185310_102.jpg", title="Hand-Stained Finish", category="Framing", desc="Custom mixed stain to match the client's existing furniture.", aspect="aspect-[4/3]"),
    PortfolioItem(id=22, file="IMG-20180414-WA0023.jpg", title="Wedding Photo Series", category="Framing", desc="Elegant and romantic framing for wedding photography.", aspect="aspect-square"),
    PortfolioItem(id=23, file="IMG-20180414-WA0024.jpg", title="Family Heritage", category="Framing", desc="Preserving old family photographs with archival standards.", aspect="aspect-[3/4]"),
    PortfolioItem(id=24, file="IMG-20180415-WA0020.jpg", title="Artist Showcase", category="Framing", desc="Framing designed to let the art speak for itself.", aspect="aspect-[4/3]"),
    PortfolioItem(id=25, file="IMG-20180526-WA0038.jpg", title="Bold Color Choice", category="Framing", desc="A vibrant frame color chosen to pop against a neutral wall.", aspect="aspect-square"),
    PortfolioItem(id=26, file="IMG-20180528-WA0014.jpg", title="Subtle Elegance", category="Framing", desc="Understated design that complements rather than competes.", aspect="aspect-[3/4]"),
    PortfolioItem(id=27, file="IMG-20180611-WA0045.jpg", title="Workshop Process", category="Maintenance", desc="Behind the scenes in our woodshop.", aspect="aspect-[4/3]"),
    PortfolioItem(id=28, file="IMG-20180611-WA0046.jpg", title="Precision Cutting", category="Maintenance", desc="Ensuring every angle is perfect for a seamless joint.", aspect="aspect-square"),
    PortfolioItem(id=29, file="IMG-20180611-WA0047.jpg", title="Final Assembly", category="Maintenance", desc="The final touches before the piece is ready for delivery.", aspect="aspect-[3/4]"),
    PortfolioItem(id=30, file="IMG-20180908-WA0022.jpeg", title="Showcase Piece", category="Maintenance", desc="The finished work ready to be displayed in the client's home.", aspect="aspect-[4/3]"),
]

moldings: list[Molding] = [
    Molding(name="Dark Walnut", file="/assets/moldings/walnut.svg", category="Wood"),
    Molding(name="Classic Oak", file="/assets/moldings/oak.svg", category="Wood"),
    Molding(name="Cherry Wood", file="/assets/moldings/cherry.svg", category="Wood"),
    Molding(name="Classic Crown", file="/assets/moldings/crown_molding.svg", category="Wood"),
    Molding(name="Maple Base", file="/assets/moldings/baseboard.svg", category="Wood"),
    Molding(name="Mahogany Rail", file="/assets/moldings/chair_rail.svg", category="Wood"),
    Molding(name="Gold Leaf", file="/assets/moldings/gold.svg", category="Metallic"),
    Molding(name="Light Ash", file="/assets/moldings/ash.svg", category="Wood"),
    Molding(name="Natural Bamboo", file="/assets/moldings/bamboo.svg", category="Wood"),
    Molding(name="Beechwood", file="/assets/moldings/beech.svg", category="Wood"),
    Molding(name="Birch", file="/assets/moldings/birch.svg", category="Wood"),
    Molding(name="Cedar", file="/assets/moldings/cedar.svg", category="Wood"),
    Molding(name="Dark Ebony", file="/assets/moldings/ebony.svg", category="Wood"),
    Molding(name="Elm", file="/assets/moldings/elm.svg", category="Wood"),
    Molding(name="Hickory", file="/assets/moldings/hickory.svg", category="Wood"),
    Molding(name="Ironwood", file="/assets/moldings/ironwood.svg", category="Wood"),
    Molding(name="Dark Mahogany", file="/assets/moldings/mahogany_dark.svg", category="Wood"),
    Molding(name="Light Maple", file="/assets/moldings/maple_light.svg", category="Wood"),
    Molding(name="Pine", file="/assets/moldings/pine.svg", category="Wood"),
    Molding(name="Poplar", file="/assets/moldings/poplar.svg", category="Wood"),
    Molding(name="Redwood", file="/assets/moldings/redwood.svg", category="Wood"),
    Molding(name="Rosewood", file="/assets/moldings/rosewood.svg", category="Wood"),
    Molding(name="Sycamore", file="/assets/moldings/sycamore.svg", category="Wood"),
    Molding(name="Teak", file="/assets/moldings/teak.svg", category="Wood"),
    Molding(name="Wenge", file="/assets/moldings/wenge.svg", category="Wood"),
    Molding(name="Zebrawood", file="/assets/moldings/zebrawood.svg", category="Wood"),
    Molding(name="Brushed Silver", file="/assets/moldings/silver.svg", category="Metallic"),
    Molding(name="Antique Bronze", file="/assets/moldings/bronze.svg", category="Metallic"),
    Molding(name="Copper", file="/assets/moldings/copper.svg", category="Metallic"),
    Molding(name="Rose Gold", file="/assets/moldings/rose_gold.svg", category="Metallic"),
    Molding(name="Platinum", file="/assets/moldings/platinum.svg", category="Metallic"),
    Molding(name="Matte Black", file="/assets/moldings/black_matte.svg", category="Painted"),
    Molding(name="Matte White", file="/assets/moldings/white_matte.svg", category="Painted"),
    Molding(name="Distressed White", file="/assets/moldings/distressed_white.svg", category="Painted"),
    Molding(name="Charcoal", file="/assets/moldings/charcoal.svg", category="Painted"),
    Molding(name="Navy Blue", file="/assets/moldings/navy_blue.svg", category="Painted"),
    Molding(name="Forest Green", file="/assets/moldings/forest_green.svg", category="Painted"),
]

mat_color_groups: list[MatColorGroup] = [
    MatColorGroup(name="Neutrals", colors=[
        MatColor(name="Pure White", value="#FFFFFF"),
        MatColor(name="Antique White", value="#F5F5F0"),
        MatColor(name="Cream", value="#FFFDD0"),
        MatColor(name="Soft Gray", value="#D3D3D3"),
        MatColor(name="Charcoal", value="#36454F"),
        MatColor(name="Gallery Black", value="#1a1a1a"),
    ]),
    MatColorGroup(name="Bolds", colors=[
        MatColor(name="Navy Blue", value="#1B2A4A"),
        MatColor(name="Burgundy", value="#4A1B1B"),
        MatColor(name="Forest Green", value="#1B3022"),
        MatColor(name="Deep Plum", value="#361B30"),
    ]),
    MatColorGroup(name="Earthy", colors=[
        MatColor(name="Sage Green", value="#8A9A5B"),
        MatColor(name="Ochre", value="#CC7722"),
        MatColor(name="Terracotta", value="#E2725B"),
        MatColor(name="Slate Blue", value="#708090"),
    ]),
]

services: list[Service] = [
    Service(title="Custom Framing", description="Tailored frames designed to perfectly complement and protect your artwork, using premium hardwoods like Walnut, Oak, and Mahogany.", icon="Ruler"),
    Service(title="Large-Scale Frames", description="Specialized structural framing for oversized pieces, ensuring stability and visual impact without compromising elegance.", icon="Image"),
    Service(title="Artistic Mounting", description="Museum-quality mounting techniques that preserve the integrity of your pieces while enhancing their presentation.", icon="Palette"),
]
